const knownLanguages = {
  'json': { id: 'json', order: 0, label: 'JSON' },
  'yaml': { id: 'yaml', order: 1, label: 'YAML' },
  'jsonld': { id: 'jsonld', order: 3, label: 'JSON-LD', highlight: 'json' },
  'turtle': { id: 'turtle', order: 4, label: 'RDF/Turtle' },
  'plaintext': { id: 'plaintext', order: 5, label: 'Plain text' },
  'java': { id: 'java', order: 6, label: 'Java' },
  'python': { id: 'python', order: 7, label: 'Python' },
  'javascript': { id: 'javascript', order: 8, label: 'Javascript' },
  'bash': { id: 'bash', order: 9, label: 'Bash' },
  'geojson': { id: 'geojson', order: 2, label: 'GeoJSON', highlight: 'json' },
  'xml': { id: 'xml', order: 10, label: 'XML' },
  'html': { id: 'html', order: 11, label: 'HTML', highlight: 'xml' },
  'css': { id: 'css', order: 12, label: 'CSS' },
  'typescript': { id: 'typescript', order: 13, label: 'TypeScript' },
  'sql': { id: 'sql', order: 14, label: 'SQL' },
  'sparql': { id: 'sparql', order: 15, label: 'SPARQL' },
  'jq': { id: 'jq', order: 16, label: 'jq' },
  'markdown': { id: 'markdown', order: 17, label: 'Markdown' },
  'graphql': { id: 'graphql', order: 18, label: 'GraphQL' },
  'ruby': { id: 'ruby', order: 19, label: 'Ruby' },
  'go': { id: 'go', order: 20, label: 'Go' },
  'rust': { id: 'rust', order: 21, label: 'Rust' },
  'cpp': { id: 'cpp', order: 22, label: 'C++' },
  'c': { id: 'c', order: 23, label: 'C' },
  'kotlin': { id: 'kotlin', order: 24, label: 'Kotlin' },
  'swift': { id: 'swift', order: 25, label: 'Swift' },
  'scala': { id: 'scala', order: 26, label: 'Scala' },
  'r': { id: 'r', order: 27, label: 'R' },
  'lua': { id: 'lua', order: 28, label: 'Lua' },
  'perl': { id: 'perl', order: 29, label: 'Perl' },
  'php': { id: 'php', order: 30, label: 'PHP' },
  'wasm': { id: 'wasm', order: 31, label: 'WebAssembly' },
  'xquery': { id: 'xquery', order: 32, label: 'XQuery' },
  'latex': { id: 'latex', order: 33, label: 'LaTeX' },
  'protobuf': { id: 'protobuf', order: 34, label: 'Protocol Buffers' },

  // file extension aliases
  'ttl': 'turtle',
  'json-ld': 'jsonld',
  'yml': 'yaml',
  'txt': 'plaintext',
  'js': 'javascript',
  'ts': 'typescript',
  'md': 'markdown',
  'rb': 'ruby',
  'rs': 'rust',
  'kt': 'kotlin',
  'rdf/turtle': 'turtle',
  'htm': 'html',
  'pgsql': 'sql',
  'postgres': 'sql',

  // MIME type aliases
  'application/json': 'json',
  'application/geo+json': 'geojson',
  'application/yaml': 'yaml',
  'application/xml': 'xml',
  'application/javascript': 'javascript',
  'application/typescript': 'typescript',
  'application/sql': 'sql',
  'application/sparql-query': 'sparql',
  'application/sparql-update': 'sparql',
  'application/graphql': 'graphql',
  'application/wasm': 'wasm',
  'application/xquery': 'xquery',
  'application/x-latex': 'latex',
  'application/protobuf': 'protobuf',
  'application/x-python': 'python',
  'application/x-httpd-php': 'php',
  'text/xml': 'xml',
  'text/html': 'html',
  'text/css': 'css',
  'text/javascript': 'javascript',
  'text/typescript': 'typescript',
  'text/markdown': 'markdown',
  'text/x-sql': 'sql',
  'text/x-python': 'python',
  'text/x-ruby': 'ruby',
  'text/x-go': 'go',
  'text/x-rust': 'rust',
  'text/x-c++src': 'cpp',
  'text/x-csrc': 'c',
  'text/x-java': 'java',
  'text/x-java-source': 'java',
  'text/x-kotlin': 'kotlin',
  'text/x-swift': 'swift',
  'text/x-scala': 'scala',
  'text/x-r': 'r',
  'text/x-lua': 'lua',
  'text/x-perl': 'perl',
  'text/x-php': 'php',
  'text/x-latex': 'latex',
  'text/turtle': 'turtle',
  'shell': 'bash',
  'sh': 'bash',
};

const getHighlightLanguage = lang => {
  let l = knownLanguages[lang];
  if (typeof l === 'string') {
    l = knownLanguages[l];
  }
  if (l) {
    return l.highlight || l.id;
  }
  return lang;
};

const geoJsonLanguageIds = new Set(['json', 'jsonld', 'geojson']);

export { knownLanguages, getHighlightLanguage, geoJsonLanguageIds };
