name: Create dist

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    concurrency:
      group: dist
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies and build
        run: |
          npm install
          VITE_DYNAMIC_BASE_URL=true yarn build
          cp dist/index.html dist/404.html
      - name: Push to dist
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
